feat: add moving tape with market info [SF-1278]
Secured-Finance/secured-finance-app pull request #692
Opened 2024-12-26 10:08 UTC by vijayeth

Added market info in moving tape. Markets are clickable and navigates to their page on click.

2025-01-08 07:24 UTC, biga816 requested changes

2025-01-08 07:24 UTC, biga816 commented on src/components/pages/Landing/Landing.tsx
> +                }}
In the React code, it's better not to change styles directly like JS-style in terms of readability.

2025-01-08 07:24 UTC, biga816 commented on src/components/pages/Landing/Landing.tsx
> +                className='ml-[100px] inline-block animate-scroll-left whitespace-nowrap'
It looks like the font size is a bit large. How bout setting `text-xs` here?

2025-01-09 09:13 UTC, vijayeth commented on src/components/pages/Landing/Landing.tsx
> +                }}
fixed in fd8045afdcd09afa049c41c5a033239c94cbe0c4

2025-01-09 09:13 UTC, vijayeth commented on src/components/pages/Landing/Landing.tsx
> +                className='ml-[100px] inline-block animate-scroll-left whitespace-nowrap'
fixed in fd8045afdcd09afa049c41c5a033239c94cbe0c4

2025-01-19 18:34 UTC, closed without merging